apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-service
  labels:
    app: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: cluster
      port: 16379
      targetPort: 16379
      protocol: TCP
  clusterIP: None
  selector:
    app: redis
